### ISSUE TITLE
Customise Torrent Search-Engines list

### ISSUE THREAD

**Issue by TtuxX** [shiningw/ncdownloader#1]
Hi @shiningw ! :)

Thank you very much for this great new app ! 

The possibility to search torrents online is a great option. 

Would it be possible to insert all the torrent search engines we want to add (1 per line) in a customisable settings field?
The idea would be that each user could then add all the search engines they want in the following way:

https://mirrorbay.top/search.php?q=USERINPUT
https://xxxxxxx.xx/search.php?request=USERINPUT
...

And then when searching, the NCDownloader app could fetch results one SE after the other and display and sort results live with a progress bar/indicator for the user, displaying:
"Fetching torrent from search-engine 1/5 ..."

Thank you so much in advance for your kind help and thanks again for your great app ! :)

**Comment by shiningw** [comment]
@TtuxX 
Hi, Your feedback is much appreciated! Currently it searches thepiratebay site for torrent results. As we need a set of predefined rules to scrape data, it is not possible for users to enter random sites and start searching.  But I'm planning to add more sites in later versions. Thank you!

**Comment by TtuxX** [comment]
Arf, of course regarding scraping, my bad !

Maybe then it could be great to have also a torrent meta search-engine kind of like https://bitsearch.to/ or something similar ?

Thank you very much for the development of this great downloader !
We the community had only OCDownloader as a solution, left in a pretty bad state since many years (https://www.reddit.com/r/NextCloud/comments/6fyoh0/is_there_any_fix_for_ocdownloader/) and I must say it is a happy surprise and real pleasure to discover your super downloader project. Keep up the great work ! :)

**Comment by shiningw** [comment]
the latest release has added bitsearch.to. Now you can select a site and search for torrents in it.

**Comment by TtuxX** [comment]
Thank you very much ! :)
