### ISSUE TITLE
[Youtube] Unable to extract uploader id

### ISSUE THREAD

**Issue by medismail** [shiningw/ncdownloader#112]
**Describe the bug**
ERROR youtube: Unable to download video 

**To Reproduce**
1. Go to 'Youtube-dl'
2. Click on 'Download'
3. See error 'ERROR: [youtube] _55GOq3QALI: Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U'

**Expected behavior**
Download the file

**Desktop:**
 - Browser chrome

**Additional context**
The bug is in yt-dlp: [Youtube] Unable to extract uploader id https://github.com/yt-dlp/yt-dlp/issues/6247

**Comment by amiroof** [comment]
did you find any fix for it?
i can dl videos from terminal using youtube-dl (or yt-dlp) but ncdownloader seems to have an issue and throws the error.

**Comment by amiroof** [comment]
UPDATE: I managed to fix this issue by replacing `yt-dlp` located in `/var/www/htm/nextcloud/apps/ncdownloader/bin` with the latest release and then running `sudo chmod 755 /var/www/htm/nextcloud/apps/ncdownloader/bin/yt-dlp`.
Everythings fine now.

**Comment by medismail** [comment]
Fixed
