### ISSUE TITLE
Add support for ARM architecture

### ISSUE THREAD

**Issue by pktiuk** [shiningw/ncdownloader#117]
**Is your feature request related to a problem? Please describe.**
I host my NC instance on ARM server

**Describe the solution you'd like**
Include ARM version of binaries like ARIA2

**Comment by pktiuk** [comment]
After downloading proper aria2  package I got error `failed to download the file for some reason!` when I wanted to use a torrent

**Comment by shiningw** [comment]
yes, the included binaries are not built to work on the ARM platform!

**Comment by pktiuk** [comment]
But what about adding support for ARM?    
(consider this issue as a feature request)
