### ISSUE TITLE
Youtube-dl binary

### ISSUE THREAD

**Issue by gklimm** [shiningw/ncdownloader#121]
No matter what is set in the admin settings for "Youtube-dl binary", the yt-dlp in the bin directory is always called first. this does not work for zoom, for example.
yt-dlp with a link to /usr/local/bin/ytdl-patched works fine, but is dirty. It would be nicer if the entry in the administration was also used.

**Comment by shiningw** [comment]
Hi,
This is caused by a stupid bug which I'll fix soon. Thank you!
