### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by themetalleg** [shiningw/ncdownloader#122]
**Describe the bug**
Nextcloud is not working after updating to the new version showing a white webpage.

**To Reproduce**
1. update to the new version in nextcloud
2. open your nextcloud through the browser
3. see white page

**Expected behavior**
Nextcloud webpage should be displayed normally.

**Desktop (please complete the following information):**
 - OS: windows / linux
 - Browser firefox
 - Version 26

**Additional context**
I tried then to list the apps via: sudo -u www-data php occ app:list
and got the following error:

PHP Fatal error:  Cannot declare class OCA\NCDownloader\AppInfo\Application, because the name is already in use in /var/www/nextcloud/apps/ncdownloader/lib/appinfo/application.php on line 17

**Comment by themetalleg** [comment]
This is how it worked for me:

Navigate to the ncdownloader app directory:

`cd /var/www/nextcloud/apps/ncdownloader`

Rename the application.php file to something else, for example:

`mv lib/appinfo/application.php lib/appinfo/ncdownloader_application.php`

Run the app:disable command for the ncdownloader app:

`sudo -u www-data php occ app:disable ncdownloader`

Clear the Nextcloud cache:

```
sudo -u www-data php occ maintenance:mode --on
sudo -u www-data php occ maintenance:repair
sudo -u www-data php occ maintenance:mode --off
```

Verify that the ncdownloader app is no longer listed in the output of app:list.

You can then try renaming the ncdownloader_application.php file back to application.php, and then re-enable the ncdownloader app:

```
mv lib/appinfo/ncdownloader_application.php lib/appinfo/application.php
sudo -u www-data php occ app:enable ncdownloader
```

Clear the Nextcloud cache again:

```
sudo -u www-data php occ maintenance:mode --on
sudo -u www-data php occ maintenance:repair
sudo -u www-data php occ maintenance:mode --off
```

Verify that the ncdownloader app is now listed as enabled.

**Comment by shiningw** [comment]
Hi,
Sorry, I moved the same file from appinfo into lib/appinfo by mistake. it will be fixed in minutes. Thank you!
