### ISSUE TITLE
[User Experience] New appearence for NCDownloader

### ISSUE THREAD

**Issue by TtuxX** [shiningw/ncdownloader#13]
Hi @shiningw ! :)

I love your application and I love using it, thank you so much for developing it and being so reactive!

Following the improvement suggestion regarding issue #11, I started thinking a bit more about how to make your great app even better. I digged into the topic maybe a bit too much and ended-up reworking the whole download page design and user experience (only a drawing).

- ### New NCDownloader overall appearence illustration:

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6570830/136968406-a4b7e2f8-03ec-45e5-8c9d-3ab95356d89f.png">

    - Main reasons and advantages behing this new appearence:
        - Sidebar:
            - Only 1 button for downloads and 1 for searching torrents,
            - Settings moved at the bottom of the page to respect Nextcloud design layouts,
            - "Stop Aria" button moved to settings (not something we enable/disable often),
         - Main panel:
            - One central place for all the types of downloads while keeping visual space clear,
            - Reactive components and options that change/appear/disappear live
              (avoid useless page reloads and too many options displayed),
            - A "control zone" that validates inputs, files availability and so on
              (just before the download button to catch errors early 
               and as they arrive). This zone could also help debugging.

Breaking it down further into details, please kindly find hereunder the new user experience I imagined:

- ### Step-by-step new user experience for NCDownloader:

_**NOTE: pages number 1, 2, 3 is the same page (should happen without page reload). The numbers only indicate the main process steps for the download of a file. Everything in dark blue is a comment.**_

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6570830/136969554-370d3925-d32c-4502-84db-4c1da7a9640e.png">

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6570830/136969961-5766299a-6ceb-4399-a024-4421929fab0a.png">

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6570830/136970743-7eb9d6af-e13d-478a-99d4-eebed91a7db5.png">

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6570830/136970782-1b00ac44-b26d-4568-8bc3-54d8eabb6bc6.png">

I know this design would be a huge change with many implications and I hope you will not find it too bad.

Anyway thank you so much again for all the work you do on your Downloader and for the time you spend solving the community issues!

I remain at your entire disposal to help you in any manner I can and to work on any design detail.

Kind regards

TtuxX

**Comment by shiningw** [comment]
Hello,
what you suggested are sensible and feasible, and I will try to work on it when the core features are stable and free of bugs. For the time being, I have to say it's not top of the list. So is allowing for uploading torrent files. By the way, we will be happy to see your mobile design if it is at your convenience. Thank you!
