### ISSUE TITLE
NCDownloader not working after update to NC27

### ISSUE THREAD

**Issue by JoshuaPettus** [shiningw/ncdownloader#135]
**Describe the bug**
After upgrading to NC27 from NC26.0.3 nextcloud gets really unhappy.  The log starts throwing out the same error and every occ command does the same until I disable the app.

```
An unhandled exception has been thrown:
OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/nextcloud/apps/ncdownloader/appinfo/application.php in /var/www/nextcloud/lib/autoloader.php:141
Stack trace:
#0 /var/www/nextcloud/lib/autoloader.php(166): OC\Autoloader->isValidPath()
#1 [internal function]: OC\Autoloader->load()
#2 /var/www/nextcloud/lib/private/ServerContainer.php(106): class_exists()
#3 /var/www/nextcloud/lib/private/ServerContainer.php(186): OC\ServerContainer->getAppContainer()
#4 /var/www/nextcloud/lib/private/ServerContainer.php(153): OC\ServerContainer->getAppContainerForService()
#5 /var/www/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#6 /var/www/nextcloud/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#8 /var/www/nextcloud/occ(11): require_once('...')
#9 {main}
```

I am using NC27.0.0, PHP-8.2.7,  PostgreSQL 15.3,  Ubuntu 22.04.2

**Comment by JoshuaPettus** [comment]
Funny, I didn't have any issues in NC26, or maybe it just didn't fail catastrophically

**Comment by 31337-4554551n** [comment]
Also broken for me on version 27.
I love this app and would really appreciate it if it could be updated to continue working

**Comment by Root-Core** [comment]
There was some fix for #131 in 0c72616da75b393683e4ee8ecb7f4a5f0372edbd, but I'm not sure it's working for me. I have manually patched the line and the issue is still present on 27.0.0 @ php8.2-fpm. Hadn't had the time to further investigate though.

**Comment by edsonsbj** [comment]
People, I think I found the error when you install ncdownload through the app store, the version is 0.9.0, so that on the website https://apps.nextcloud.com/, the version is 1.0.7, when you install the version from the appstore gives this error and when you download it directly from the site it worked for me for a few days on Nextcloud 27 but as I had to restore my nextcloud instance for other reasons, I can no longer activate 1.0.7 regarding the error of 0.9.0 over PHP 8.1 I didn't understand very well because I had the version on nextcloud 26 with PHP 8.2 and I didn't see these errors

**Comment by Root-Core** [comment]
@edsonsbj I can not confirm that, on my server version 1.0.7 is installed from the app store. (Which is not working..)

**Comment by darkpisto** [comment]
There is difference between the last release version from github (1.0.6) and from the nextcloud store (1.0.7), and i guess it is something connected with this bug.
When i delete/reinstall from the store app, i got the version 0.9.0 .
When i delete/reinstall manually from a specific version on the app store, the name is "1.0.7" but the URL is "https://github.com/shiningw/ncdownloader/releases/download/v1.0.6/ncdownloader-release.tar.gz"

Maybe Shiningw have pushed a version, change his mind and delete the 1.0.7 ?

**Comment by weasam** [comment]
the release from github 1.0.6 but when upload to nextcloud it's version 1.0.7. it's wrong number?
this #131 solution still have internal server error.

**Comment by Happyfeet01** [comment]
Maybe this Thread helps? Apparently the folder structure was changed, that's why it doesn't seem to work anymore. https://github.com/nextcloud/server/issues/38797

**Comment by JoshuaPettus** [comment]
I just tried the new 1.0.20 that was just released.  It seems to be working now on NC27.  (with PHP8.2 ftr)
