### ISSUE TITLE
docker nextcloud 27.0.2 not working with ncdownloader 1.0.20

### ISSUE THREAD

**Issue by zoutao98** [shiningw/ncdownloader#142]
![图片](https://github.com/shiningw/ncdownloader/assets/46660687/ed6f1c37-7e08-4e33-a76a-4fa7a1fa7661)

**Comment by kn0wmad** [comment]
Experiencing the same, any ideas on this?  I'd love to help get it functional again

**Comment by zoutao98** [comment]
I just use aria2c rpc client and then use samba to share it. Give up nextcloud.
