### ISSUE TITLE
Cannot download anything with v1.0.20 on NC 27.0.2

### ISSUE THREAD

**Issue by ahangarha** [shiningw/ncdownloader#144]
**Describe the bug**
None of the download methods work. In the case of torrent and HTTP download, NCDownloader says that the download is finished, but no file gets saved.

**To Reproduce**
Just put a link for HTTP download. Download it and check if it exists in the destination folder.

**Expected behavior**
Simply work.

**Comment by ferritopia** [comment]
Did you see any error messages or notification when opening the NcDownloader page or when downloading?

**Comment by ahangarha** [comment]
- No error when opening Ncdownloader
- Error with YouTube-dl:
    ```
    WARNING: [youtube] unable to extract initial player response; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
    WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/0a835141.json' failed: Traceback (most recent call last):
    File "/var/www/nextcloud/apps/ncdownloader/lib/Ytdl/../../bin/yt-dlp/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
    File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
    File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
    File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/var/www/.cache'
    ```

    This could be ytdl issue, but the last line of the following error might be more helpful:

    ```
    WARNING: [youtube] unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
    ERROR: unable to create directory [Errno 17] File exists: '/tmp/oc_tmp_uasecV'
    ```
- Direct and Torrent download doesn't show any error. It shows as if the download is completed but nothing get saved in the destination directory. I have changed the destination multiple times but it didn't solve the issue.

**Comment by ahangarha** [comment]
I think the v1.0.21 release has fixed the issue. At least I have no issue on NextCloud 29.
