### ISSUE TITLE
Add support of PHP8.2+

### ISSUE THREAD

**Issue by Albirew** [shiningw/ncdownloader#160]
**Is your feature request related to a problem? Please describe.**
`App "NCDownloader" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 8.2 is required.`

**Describe the solution you'd like**
PHP8.3+ support

**Describe alternatives you've considered**
not much aside not using ncdownloader

**Additional context**
n/a

**Comment by axelmiami** [comment]
and for me!

**Comment by Happyfeet01** [comment]
#165 fix this

**Comment by Albirew** [comment]
Thanks, will close this issue when PR is merged.

**Comment by Happyfeet01** [comment]
> Thanks, will close this issue when PR is merged.

It's merged
