### ISSUE TITLE
How to use it when nextcloud run in docker

### ISSUE THREAD

**Issue by fffcoder** [shiningw/ncdownloader#17]
When I run nextcloud in docker, ncdownload can't find aria2;
so I write a Dokerfile like this:
`
From nextcloud:apache
RUN apt update && apt install -y sudo aria2
`
After recreating docker container,  ncdownload can find aria2,  but it can't bring up aria2;

How to make it work?

**Comment by shiningw** [comment]
Hi,

I'm not familiar with docker but I have tried the followings steps in Ubuntu docker installation and it works

enter the nextcloud container and run:
`docker exec -it CONTAINER_ID bash`
then install aria2
`apt -y install aria2`
