### ISSUE TITLE
Unable to detect aria2c installation

### ISSUE THREAD

**Issue by Maxwellads** [shiningw/ncdownloader#19]
Nextcloud 22.2.3 (Snap)
Ubuntu 20.04, Logged as nextcloud admin.
NCdownloader suggests that "Aria2 is not installed!" And cannot start a download, "Download failed for some reason". In fact, I installed Aria2 by APT, and I can easily fire it up by "aria2c".

**Comment by mr-scientific** [comment]
I have the same issue, help would be appreciated, aria2c works fine in the command line, but ncdownloader can't seem to detect it

**Comment by Maxwellads** [comment]
> I have the same issue, help would be appreciated, aria2c works fine in the command line, but ncdownloader can't seem to detect it

So it looks like aria2c has to be ran as a daemon and enable rpc so that the downloader can detect and use it. You can run the following command to enable it (once):
`aria2c --daemon --enable-rpc=true`

But of course, you will need to run it every time your server booted. Create a service to execute the command on-boot might help.

**Comment by shiningw** [comment]
NCDownloader currently doesn't work properly with the snap version of nextcloud as it is unable to access and execute binary files outside the sandbox. You may try the docker version if you want an easy installation of nextcloud.
