### ISSUE TITLE
Automatically start Aria2

### ISSUE THREAD

**Issue by TtuxX** [shiningw/ncdownloader#20]
Hi there @shiningw :)

I hope you are doing fine.

Would it be possible to automatically start Aria2 ? Currently I have to start it manually prior to doing anything with the app.

Would it be possible to tick a case to enable autostart, passing the Aria2 command to the next Cron job runned by Nextcloud ?

Thank you very much in advance :)

**Comment by shiningw** [comment]
Hello,
   You can configure your system to start Aria2 on boot if you want. It's not easy to do this from the web. By the way, most  of us install nextcloud on a server which is running around the clock, and you can start it once and it will keep running before you power off your server
