### ISSUE TITLE
Youtube-DL gives WARNING: unable to download video info webpage: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by Quinten0508** [shiningw/ncdownloader#21]
Full error message:
```
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: 'NoneType' object has no attribute 'get'
```

Whenever I fill in a youtube link (example: https://www.youtube.com/watch?v=JFA_pYSLl3Y) NCDownloader gives this error. Demonstration: https://streamable.com/zxbg7x

Using NextCloudPi 22.2.2 on a Raspberry Pi 4B 4GB model.

**Comment by Quinten0508** [comment]
By the way, where is the full log which NCDownloader stores located? I'm assuming it got truncated in the webui.

**Comment by shiningw** [comment]
Hello,
I tried your link and can download it with no issues. Please make sure that you can download this video using youtube-dl on the command line 
<img width="562" alt="2022-01-28 143026" src="https://user-images.githubusercontent.com/3911975/151499035-8e2579b6-eccc-41eb-b0c1-a7aa321ec498.png">
