### ISSUE TITLE
Propose regex to auto name files

### ISSUE THREAD

**Issue by darkpisto** [shiningw/ncdownloader#22]
It would be nice to add an option to youtube-dl button with files patterns names by default, like : 
'%(title)s by %(uploader)s on %(upload_date)s in %(playlist)s.%(ext)s' 
This syntax is already implemented in youtube-dl (option -o), it will be great to add an input text to configure this.
Thanks you :)

**Comment by shiningw** [comment]
Now you can set your own out template like this 
<img width="365" alt="2022-01-28 211227" src="https://user-images.githubusercontent.com/3911975/151553757-e120ca38-2bd1-494a-a9af-8e3e6ce483c6.png">

**Comment by darkpisto** [comment]
Perfect, thanks you :)
