### ISSUE TITLE
Youtube-dl downloads stuck

### ISSUE THREAD

**Issue by AlexZorzi** [shiningw/ncdownloader#24]
i have several youtube-dl files stuck, im not able to remove them, i tried to uninstall the plugin but nothing happens they appear again when i install the plugin back.
is there a way to reset the plugin?

the screenshot shows the speed but its actually stuck like that

![2022-02-07_12-47](https://user-images.githubusercontent.com/47613715/152782542-6fc437e2-7cb1-407b-87a0-03c728bf65ae.png)
?

**Comment by AlexZorzi** [comment]
fixed by editing the table at `oc_ncdownloader_info` , maybe it would be nice to have a reset button in the plugin settings

**Comment by JoshuaPettus** [comment]
or better yet have delete be an option even if the file isn't completely downloaded
