### ISSUE TITLE
[Improvement]Disable Torrent download as admin

### ISSUE THREAD

**Issue by DEAD1SIDE** [shiningw/ncdownloader#3]
It would be nice to have the option to disable Torrent download for the App

**Comment by WereCatf** [comment]
This and enforcing download-speed limits are the features I came here to check as to whether this thing supports such. Allowing my users to download Youtube-videos or such via a simple UI would be nice, but torrents are a big no-no and I'd want to enforce a speed-limit as well.

**Comment by darkpisto** [comment]
It should be a good feature :)
