### ISSUE TITLE
500 error when polling status/active

### ISSUE THREAD

**Issue by Shotman** [shiningw/ncdownloader#34]
When going on the menu to list the active or completed downloads NCDownloader makes a request to apps/ncdownloader/status/active  but it returns a 500 error so the javascript crashes and I can't see/manage my downloads

**Comment by shiningw** [comment]
Hi,
make sure your install nc correctly

**Comment by Shotman** [comment]
> Hi, make sure your install nc correctly
Not really helpfull ...
I just installed NCDownloader from Nextcloud app managment page
Installed Aria2 on the system
Setup the RPC password and location in the admin settings
I don't know how it could have been done otherwise. 
And neither this github repo and the nextcloud app page, gives the correct way to install it !

Even after doing the update on the nextcloud admin panel to 0.8 it's the same

**Comment by shiningw** [comment]
Hi,
Have you installed php-curl in your system? are there any errors in nextcloud log file? Also, please tell us more about how you install your nextcloud, snap, docker or conventional web enviroment?   

    You don't need to install Aria2 manually if the built-in ones work
