### ISSUE TITLE
python is not installed 

### ISSUE THREAD

**Issue by darkpisto** [shiningw/ncdownloader#35]
Each time i go to the NCDownloader on my nextcloud instance, i have got the following message : 
python is not installed✖

But on my server, when i launch : 
sudo apt-get install python3

I got : 
python3 est déjà la version la plus récente (3.9.2-3).

And NCDownloader seems to work properly.

(sorry if i d'ont speak english very well, and thanks you for your very good work :) )

**Comment by shiningw** [comment]
Hi,
 For the time being, you can hide the error by enabling the hide errors option in settings(settings > hide errors). The next version should resolve this issue by checking for the presence of either Python or Python3. Thank you!

**Comment by darkpisto** [comment]
Thanks you for your quick response :)

**Comment by darkpisto** [comment]
https://stackoverflow.com/questions/3655306/ubuntu-usr-bin-env-python-no-such-file-or-directory
I use this ;)

This part : 

```
    If Python 3 has been installed, run these commands: whereis python3

    Then we create a symlink to it: sudo ln -s /usr/bin/python3 /usr/bin/python
```
