### ISSUE TITLE
Use yt-dlp insteed of youtube-dl

### ISSUE THREAD

**Issue by darkpisto** [shiningw/ncdownloader#36]
A fork of youtube-dl exist : https://github.com/yt-dlp/yt-dlp
It's more often updated and have a better downloading speed (43Mo/s VS 100Ko/s for me) .
If you want and if it's not too much work (i have no idea), this should be a good alternative :)

**Comment by shiningw** [comment]
Hi,
I will try this alternative and replace the original one with it if it works well! Thank you

**Comment by darkpisto** [comment]
Great, thanks you :)
