### ISSUE TITLE
youtube-dl downloads don't render in menu

### ISSUE THREAD

**Issue by JoshuaPettus** [shiningw/ncdownloader#38]
I am using the built in youtube-dl app
NC23
PHP 8.0
PostgreSQL 14.2

When I download a youtube video and then go to the youtube-dl section.  I see a "1" next to the menu indicating that a download is happening, but the menu page doesn't render, just a blank screen.  Also It doesn't remove itself long after the video is downloaded.  
I have to go into the database manually and remove the entry

Here is an error that pops up in the log:

[index] Error: unserialize(): Argument #1 ($data) must be of type string, resource given in file '/var/www/nextcloud/apps/ncdownloader/lib/Controller/YoutubeController.php' line 53

POST /apps/ncdownloader/youtube/get

**Comment by jhaan1979** [comment]
Got the same issue on both NCDL 0.7.5 and 0.8.6 using NC 22.2.1, PSQL 13.1.
I more or less solved it by changing line 53 in `lib/Controller/YoutubeController.php` from `$extra = unserialize($value['data']);` to `$extra = unserialize(strval($value['data']));`

**Comment by JoshuaPettus** [comment]
Ah so I wonder if it might be an issue that only effects those with PSQL?

**Comment by JoshuaPettus** [comment]
That made the item appear in downloads but the delete and "redownload" buttons are non fuctional.  I still have to remove the line from the database manually...

**Comment by shiningw** [comment]
Hi,
I guess this issue is psgsql-specific.You can try my patch and let me know if it works. Thank you!
[psgsql.patch.txt](https://github.com/shiningw/ncdownloader/files/8281057/psgsql.patch.txt)

**Comment by JoshuaPettus** [comment]
Awesome,  Thank you!

That too fixes the item display issue.   But now in my nextcloud log I'm getting:

> Error | PHP | Error: Trying  to access array offset on value of type bool at  /var/www/nextcloud/apps/ncdownloader/lib/Controller/YoutubeController.php#55 |  
> -- | -- | -- | --
> 
> Error | PHP | Error: unserialize(): Error at offset 0 of 15 bytes at /var/www/nextcloud/apps/ncdownloader/lib/Controller/YoutubeController.php#53
> 

Also, delete and redownload still do not work

**Comment by JoshuaPettus** [comment]
Thank you!  That fixed it all right!
