### ISSUE TITLE
[Improvement]Make new file when downloading the same file  again

### ISSUE THREAD

**Issue by DEAD1SIDE** [shiningw/ncdownloader#4]
When downloading a file twice the new download finishes instantly and doesnt make a new file.
![image](https://user-images.githubusercontent.com/42000678/132957225-8a485e0e-b8e3-4426-b3f0-e50fcc9dd9eb.png)
![image](https://user-images.githubusercontent.com/42000678/132957488-69a280c1-e8dc-4d80-b0c3-9110e270c675.png)
It would be nice if a number (counting up for each new file) would be added for the new file

**Comment by xeats** [comment]
Same problem here, it keeps content of the old file, increasing its size
