### ISSUE TITLE
[Issue] Youtube Downloads don't show in current or finished downloads

### ISSUE THREAD

**Issue by DEAD1SIDE** [shiningw/ncdownloader#5]
Youtube Downloads don't show in current or finished downloads.
The file gets created and downloads correctly.
![image](https://user-images.githubusercontent.com/42000678/132957585-81661c7d-31d5-40ce-a9ce-b74219fad598.png)

![image](https://user-images.githubusercontent.com/42000678/132957573-89bc08ac-bf3f-422e-8b7f-c07783e1b1b1.png)

**Comment by shiningw** [comment]
Hi, 
this is a WIP feature and should be ready soon!
