### ISSUE TITLE
Bug to download in mp3 from youtube

### ISSUE THREAD

**Issue by darkpisto** [shiningw/ncdownloader#50]
When i download a link (like : https://www.youtube.com/watch?v=DgG3k6SzD9M ) in youtuble-dl and i choose "mp4" ou "m4a" it works. But if I choose "mp3", a file is downloaded with almost the same size of the m4a but it doesn't work (impossible to read from VLC by example).

Thanks again for your work :)

**Comment by shiningw** [comment]
Hi,
I'll check it and see what I can do about it

**Comment by medismail** [comment]
It wroks for me. Do you have ffmpeg installed? 
For filename I already push a pull request for correction. 
https://github.com/shiningw/ncdownloader/pull/41

**Comment by shiningw** [comment]
Hi,
You can try @Claers PR https://github.com/shiningw/ncdownloader/pull/49. Please let me know if it works

**Comment by darkpisto** [comment]
I'm ok to try, but i don't understand what i have to do :p 
How to disable the metadata ?
I just comment the line "$this->addOption('--add-metadata');" in lib/Tools/Youtube.php ?

**Comment by darkpisto** [comment]
Since the last update it works properly oO

Thanks again and sorry for inconvenience :)
