### ISSUE TITLE
youtube-dl下载文件问题

### ISSUE THREAD

**Issue by safghdfj** [shiningw/ncdownloader#57]
youtube-dl下载文件完成后NC downloads文件夹内无文件
![image](https://user-images.githubusercontent.com/95582118/167248820-4fe2ee4a-2c3d-4371-963f-c38bc8c112dc.png)
![image](https://user-images.githubusercontent.com/95582118/167248836-76152695-ec9f-4bd5-8288-eb98c5ec894f.png)
![image](https://user-images.githubusercontent.com/95582118/167248845-723438cf-87ec-42ce-bab2-d9a87f1fe946.png)

Log 文件：
![image](https://user-images.githubusercontent.com/95582118/167249641-34d77002-ca29-4dfa-ac96-95e030c1e713.png)

**Comment by shiningw** [comment]
你好，
这个看起来像是youtube-dl的问题。可以试下把手动安装的youtube-dl删除，使用包里自带的yt-dlp
