### ISSUE TITLE
Download Youtube Videos in Nextcloud supported (playable) format

### ISSUE THREAD

**Issue by apg1980** [shiningw/ncdownloader#7]
Hello,

NCDownloader is working well, but youtube Downloads are downloadet as .mkv which is not directly playable from Nextcloud Webinterface.
Is ist possible to download it as m4v which is directly playable from NC Web?

**Comment by shiningw** [comment]
Hello,
Can you please give me a youtube link to test? Thank you!

**Comment by apg1980** [comment]
hi, here for example: https://youtu.be/aMfOCNSKn6U?list=LL

**Comment by shiningw** [comment]
![image](https://user-images.githubusercontent.com/3911975/133925902-c80fede5-bc2a-45df-bd51-8a5f803669bb.png)
![image](https://user-images.githubusercontent.com/3911975/133925932-e860f394-fbdd-4282-befc-bb489d98bce4.png)

I've tested your link and found no issue with it. It is saved in MP4 format and can be played directly in the browser

**Comment by apg1980** [comment]
unfortunatley no, the file is dispayed while downloading as mp4, but safed on nextcloud as mk4 as displayed with screenshots above
