### ISSUE TITLE
Aria2c is not running - how to autostart builtin aria2c

### ISSUE THREAD

**Issue by tquest1** [shiningw/ncdownloader#71]
It's been asked before but an explicit solution was not given. How can we make sure that the builtin aria2c that is included in the app is automatically started on server reboot. 

Our server shuts down & restarts for backups & then our users can't use ncdownloader because they are not admin users & can't start aria2 from the gui. Is there anyway this can be scripted - maybe with  a systemd file. Ideally a feature could be added to the app's config for this. I imagine almost everyone would require that aria2 runs on boot.

**Comment by shiningw** [comment]
Hi,
You can try this patch
```` diff --git a/lib/Controller/MainController.php b/lib/Controller/MainController.php
index 7d5bf0f..734e05c 100644
--- a/lib/Controller/MainController.php
+++ b/lib/Controller/MainController.php
@@ -88,7 +88,8 @@ class MainController extends Controller
                 array_push($errors, sprintf("aria2 is installed but don't have the right permissions.Please execute command sudo chmod 755 %s", $aria2_bin));
             }
             if (!$params['aria2_running']) {
-                array_push($errors, $this->l10n->t("Aria2c is not running!"));
+               // array_push($errors, $this->l10n->t("Aria2c is not running!"));
+               $this->aria2->start();
             }
         }
         if ($youtube_installed && (!$youtube_executable || !@is_readable($youtube_bin))) {`

**Comment by tquest1** [comment]
Thanks  - works great!

**Comment by afzl-wtu** [comment]
> Hi, You can try this patch
> 
> ```diff
> index 7d5bf0f..734e05c 100644
> --- a/lib/Controller/MainController.php
> +++ b/lib/Controller/MainController.php
> @@ -88,7 +88,8 @@ class MainController extends Controller
>                  array_push($errors, sprintf("aria2 is installed but don't have the right permissions.Please execute command sudo chmod 755 %s", $aria2_bin));
>              }
>              if (!$params['aria2_running']) {
> -                array_push($errors, $this->l10n->t("Aria2c is not running!"));
> +               // array_push($errors, $this->l10n->t("Aria2c is not running!"));
> +               $this->aria2->start();
>              }
>          }
>          if ($youtube_installed && (!$youtube_executable || !@is_readable($youtube_bin))) {`
> ```

How to apply this patch. which and where this file lives?
