### ISSUE TITLE
Global ARIA2C Config

### ISSUE THREAD

**Issue by MadMakz** [shiningw/ncdownloader#74]
I made the switch from OCdownloader where i was running Aria2 as a daemon with global limitations such as speed / seed limit.

Would be nice to have an option to just connect to a daemon or set global configs and therefore an option to disable per-user setting (or enfoce global settings over user)

**Comment by shiningw** [comment]
Hi,
  Ncdownloader uses its own default config to start the daemon instead of your custom config. The next update should include the ability to add user's own options
