### ISSUE TITLE
[yt-dlp] option `wait-for-video` not available

### ISSUE THREAD

**Issue by emericv** [shiningw/ncdownloader#76]
Hello,

The `yt-dlp` option `wait-for-video` is not available
![image](https://user-images.githubusercontent.com/1727636/187036127-7e69a85b-d097-4250-b099-ea84f968baf5.png)

**Comment by shiningw** [comment]
Hi,

You could add any missing options in these two files. Thank you!
[https://github.com/shiningw/ncdownloader/blob/master/src/utils/ytdlOptions.js](url)
[https://github.com/shiningw/ncdownloader/blob/master/lib/Aria2/Options.php](url)

**Comment by emericv** [comment]
@shiningw In the commit https://github.com/shiningw/ncdownloader/commit/fd774d36aa7eb2b272d7f0c006f4695c32a3906b you have deleted the `wait-for-video` option
