### ISSUE TITLE
ffmpeg is not installed

### ISSUE THREAD

**Issue by Detsle** [shiningw/ncdownloader#81]
### How can it be removed?
Good afternoon, an information window pops up with the text "**ffmpeg is not installed**".

- Nextcloud v24.0.5
- NCDownloader v1.0.1

![2022-09-21_18-06-00](https://user-images.githubusercontent.com/22348086/191540871-20caef15-02bd-4e7b-9fb1-320a20d2e84c.png)

**Comment by OSINT-Musings** [comment]
Hi,

ffmpeg is a dependency of NCDownloader. Installing the appropriate ffmpeg package on your system through the package manager will resolve this issue. On my system, Ubuntu LTS, this was resolved with the command:

> sudo apt install ffmpeg

Ensure you adapt this command for your system.

This should remove the error when you navigate to the NCDownloader application.

**Comment by Detsle** [comment]
Thanks, it helped)
