### ISSUE TITLE
Not working on Nextcloud 25

### ISSUE THREAD

**Issue by RealSerga** [shiningw/ncdownloader#85]
**Describe the bug**
Not working on NC25

**To Reproduce**
1. Install nextcloud 25
2. Install ncdownloader
3. See error on screenshot

**Expected behavior**
Normal working

**Screenshots**
![Screenshot_20221020_054233](https://user-images.githubusercontent.com/23523391/196830514-cdeb5336-e5ef-4baa-a673-3f43bfded17f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser Latest chrome

**Smartphone (please complete the following information):**
 - Device: A
 - OS: Android 12
 - Browser Latest chrome

**Additional context**
-

**Comment by darkpisto** [comment]
Before to update, we can see the following warning : 

![NCDownload_incompatible](https://user-images.githubusercontent.com/6626356/197783178-c863c7bc-dedd-44c3-97ed-4058fc37f0fe.png)

(Sorry for french :p , this just means "NCDownloader is not compatible with Nextcloud 25.0.0" )

What is required for the application to be compatible ?

Thanks in advance ;)

**Comment by Im-Toxik** [comment]
It's the same for NCDownload, OCDownload or Transfer.
It seems that Nextcloud did some major changes to the interface or file manager.
Nextcloud 24 is mostly used for now so let's wait (https://ncpw.mdns.eu/ for stats).

@darkpisto Moi j'arrive très bien à lire perso xD

**Comment by ghis94** [comment]
> It's the same for NCDownload, OCDownload or Transfer. It seems that Nextcloud did some major changes to the interface or file manager. Nextcloud 24 is mostly used for now so let's wait (https://ncpw.mdns.eu/ for stats).
> 
> @darkpisto Moi j'arrive très bien à lire perso xD

and Passwords!

@darkpisto pas de soucis non plus :p

**Comment by darkpisto** [comment]
So, for now, if we want to keep using NCDownload, we must not update to Nextcloud 25 ?
What changed impacting NCDownload ?

@Im-Toxik @ghis94 bande de franchouillards :p

**Comment by RealSerga** [comment]
Thanks!

**Comment by darkpisto** [comment]
Thanks @shiningw  :)

**Comment by Im-Toxik** [comment]
Thank you @shiningw :)
