### ISSUE TITLE
Can't change Personal Youtbue-dl Settings for non-admin users

### ISSUE THREAD

**Issue by dhuschde** [shiningw/ncdownloader#95]
**Describe the bug**
When a user isn't admin, but wants to save the youtube-dl options, nothing happens.

When you change the user to Admin, it works

**To Reproduce**
1. Go to the Personal Settings page of NCDownloader
2. Click on Add a Setting (sponsorblock-remove:all for example)
3. Click Save
4. Reload the page and see that nothing was saved.
5. Change the user to admin and repeat
6. it is saved now.

**Expected behavior**
It should save for non-admin users too

**Desktop (please complete the following information):**
 - OS: [Linux Mint 21 Cinnamon]
 - Browser [Firefox]
 - Version [107]

**Comment by shiningw** [comment]
Hi,
I'll look into it when I have time.
