### ISSUE TITLE
Internal Server Error - 24.0.7

### ISSUE THREAD

**Issue by etyrnal** [shiningw/ncdownloader#96]
I was able to install and run ncdownloader once.  And it never was able to open after that.  This is happening on TWO identical instances, running on two identical machines, running fresh installs of Ubuntu 22.04 lts, with fresh snap installs of nextcloud 24.0.7 -- i suspect it doesn't know how to handle external storage of he sftp type?

Internal Server Error [SNAP 24.0.7]
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: <redacted>
Request ID: 3QKO6Pcf0wOmb6BgyzC2

<html>
<body>

Error | index | TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class OCA\Files_External\Lib\Storage\SFTP does not have a method "getLocalFolder"/snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 527:call_user_func_array()<<closure>>OC\Files\Storage\Wrapper\Wrapper->__call()/snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 527:call_user_func_array()<<closure>>OC\Files\Storage\Wrapper\Wrapper->__call()/snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 527:call_user_func_array()/snap/nextcloud/32537/htdocs/lib/private/Files/View.php - line 264:OC\Files\Storage\Wrapper\Wrapper->__call()/snap/nextcloud/32537/htdocs/lib/private/Files/Filesystem.php - line 456:OC\Files\View->getLocalFolder()/var/snap/nextcloud/32537/nextcloud/extra-apps/ncdownloader/lib/Tools/Helper.php - line 398:OC\Files\Filesystem::getLocalFolder()/var/snap/nextcloud/32537/nextcloud/extra-apps/ncdownloader/lib/Tools/Helper.php - line 406:OCA\NCDownloader\Tools\Helper::getLocalFolder()/var/snap/nextcloud/32537/nextcloud/extra-apps/ncdownloader/lib/Tools/Helper.php - line 453:OCA\NCDownloader\Tools\Helper::getRealDownloadDir()/var/snap/nextcloud/32537/nextcloud/extra-apps/ncdownloader/appinfo/application.php - line 32:OCA\NCDownloader\Tools\Helper::getAria2Config()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 162:OCA\NCDownloader\AppInfo\Application->OCA\NCDownloader\AppInfo\{closure}("*** sensiti ... *")/snap/nextcloud/32537/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")/snap/nextcloud/32537/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 129:Pimple\Container->offsetGet()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 459:OC\AppFramework\Utility\SimpleContainer->query()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437:OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()/var/snap/nextcloud/32537/nextcloud/extra-apps/ncdownloader/appinfo/application.php - line 52:OC\AppFramework\DependencyInjection\DIContainer->query()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 162:OCA\NCDownloader\AppInfo\Application->OCA\NCDownloader\AppInfo\{closure}("*** sensiti ... *")/snap/nextcloud/32537/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")/snap/nextcloud/32537/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 129:Pimple\Container->offsetGet()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 459:OC\AppFramework\Utility\SimpleContainer->query()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437:OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 57:OC\AppFramework\DependencyInjection\DIContainer->query()/snap/nextcloud/32537/htdocs/lib/private/AppFramework/App.php - line 145:OC\AppFramework\Utility\SimpleContainer->get()/snap/nextcloud/32537/htdocs/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/snap/nextcloud/32537/htdocs/lib/base.php - line 1030:OC\Route\Router->match()/snap/nextcloud/32537/htdocs/index.php - line 36:OC::handleRequest()
-- | -- | --

</body>
</html>

**Comment by shiningw** [comment]
Hi,
You are correct that ncdownloader doesn't work with virtual fs because Aria2 and youtube-dl don't
