### ISSUE TITLE
Cannot delete folders

### ISSUE THREAD

**Issue by ze-nite** [shiningw/ncdownloader#97]
I cant delete the folder 'Downloads', I checked permissions in ubuntu and all belong to www-data, and Its not being used by NCDownloader I think.
![Captura de ecrã 2022-12-08 165621](https://user-images.githubusercontent.com/33848154/206515696-70a108fc-982c-44a1-be45-34669d177b43.png)

translation : "Error deleting file Downloads"

![Captura de ecrã 2022-12-08 165723](https://user-images.githubusercontent.com/33848154/206515733-b7798a14-e42d-40c2-8c30-90549458fdf5.png)

**Comment by ZennithPT** [comment]
I tried with other user and I can delete the folder Downloads, but in my user I cant
